version: "3.9"

services:
  suridash-backend:
    build: ./server
    container_name: suridash-backend
    restart: always
    privileged: true   # REQUIRED for ipset + iptables
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/suridash
      - PORT=3000
      - BETTER_AUTH_SECRET=random_secret_key_here
      - BETTER_AUTH_URL=http://localhost:3000
      - ORIGIN_URL=http://localhost:5173
      - DATABASE_URL=postgres://postgres:postgres@db:5432/suridash
      - BREVO_API_KEY=your_brevo_api_key_here
      - IPINFO_TOKEN=your_ipinfo_token_here
    volumes:
      - /var/log/suricata:/var/log/suricata:ro   # important for eve.json tail
    ports:
      - "3000:3000"
    depends_on:
      - db

  suridash-frontend:
    build: ./client
    container_name: suridash-frontend
    restart: always
    environment:
      - VITE_BASE_URL_API=http://localhost:3000/api
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    container_name: suridash-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: suridash
    volumes:
      - suridash-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  suridash-db-data:
